# https://moonrepo.dev/docs/config/tasks
$schema: https://moonrepo.dev/schemas/tasks.json

tasks:
    check:
        command: biome check --write

    format:
        command: biome format --write

    lint:
        command: biome lint --write
